### PR TITLE
Fix viewport on mobile

### PR DESCRIPTION
**Pull request by x1h0**

### CODE REVIEW

**Comment by rexim** [comment]
@x1h0 wasn't it already fine? People in the chat were saying that everything's fine. What's the problem this PR fixes?

**Comment by x1h0** [comment]
@rexim it was slightly cut off at the sides in portrait orientation. With the change, the page is scaled based on the browser width. This should also work in landscape.

**Comment by rexim** [comment]
@x1h0 alright let's give it a try...

**Comment by rexim** [comment]
@x1h0 I checked in an Android emulator (my real phone is too old for that) and I didn't notice much difference tbh. But ok let's just keep it. Thanks for the PR!

**Pull request merged**
